### ISSUE TITLE
"TFAR ERROR: tf_rt1523g is not a valid LR radio"

### ISSUE THREAD

**Issue by RyanWolfe556** [WolfeLib/co40WolfeLib.altis#22]
I need to look at the modules..

**Comment by RyanWolfe556** [comment]
[TFAR Classes](https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Classes) says that this is a valid LR, but it's not catching it. What do you think about a change to `tf_rt1523g_big` instead? @ZwinkaDink

**Comment by RyanWolfe556** [comment]
Strange.. It stopped showing up. May no longer be an issue

**Comment by ZwinkaDink** [comment]
solved
